name: GEARIA
favicon: null
layout_spectrum: 0.16157326637767255
typography_spectrum: 0.31931858393363655
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.7129861605353653
  lightness: 0.41235379688441753
  saturation: 0.13459141040220857
  rhythmicContrast: 0.3413668207358569
purpose: []
